### ISSUE TITLE
The password and password confirmation fields

### ISSUE THREAD

**Issue by FXStrato** [FXStrato/team-challenge#5]

**Comment by FXStrato** [comment]
Fixed password confirmation errors, and added unit testing for password validation and confirmation.

**Comment by FXStrato** [comment]
Should have been closed with my pull merge.

**Comment by camd67** [comment]
This wasn't closed with your PR since the *body* of the PR has to contain `fixes #2` or `closes #3` and so on rather than the comments themselves. The comments only reference the issue.

All your bodies were `No description provided`
